name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write  # push to gh-pages-storybook branch

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 10.27.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install and Build 🔧
        run: |
          pnpm install --frozen-lockfile
          pnpm run build:storybook
      - name: Add .nojekyll file to static folder 📁
        run:
          | # Add .nojekyll file to the static folder to prevent 404 errors (files with _ prefix are not copied to the static folder)
          touch storybook-static/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-storybook
          folder: storybook-static
          clean: true
